@startuml

title __ELEMENTS's Class Diagram__\n

  namespace Elements {
    class Elements.Day {
        - id : int
        - name : String
        + Day()
        + Day()
        + getId()
        + getName()
        + setId()
        + setName()
    }
  }
  

  namespace Elements {
    class Elements.DayParser {
        + CzyJestemSwietem()
        + DodajSwieto()
        + Edytuj()
        + IleSwiat()
        + Usun()
        + UsunSwieto()
        + createSaveQuery()
        + dodajPosilekDoDnia()
        + pobierzJeden()
        + pobierzWszystkie()
        + usunPosilekZDnia()
    }
  }
  

  namespace Elements {
    class Elements.Dish {
        - id : int
        - name : String
        + Dish()
        + Dish()
        + getId()
        + getName()
        + setId()
        + setName()
        + toString()
    }
  }
  

  namespace Elements {
    class Elements.DishParser {
        + Edytuj()
        + PobierzDaniaZPosilku()
        + Usun()
        + UsunPowiazane()
        + createSaveQuery()
        + dodajProduktDoDania()
        + pobierzJeden()
        + pobierzWszystkie()
        + usunProduktZDania()
    }
  }
  

  namespace Elements {
    class Elements.Meal {
        - id : int
        - name : String
        + Meal()
        + Meal()
        + getId()
        + getName()
        + setId()
        + setName()
        + toString()
    }
  }
  

  namespace Elements {
    class Elements.MealParser {
        + UsunPowiazane()
        + createSaveQuery()
        + dodajDanieDoPosilku()
        + edytuj()
        + pobierzJeden()
        + pobierzWszystkie()
        + usun()
        + usunDanieZPosilku()
    }
  }
  

  namespace Elements {
    class Elements.Norma {
        - carbohydrates : float
        - fat : float
        - kcal : float
        - marginesBledu : float
        - protein : float
        + Norma()
        + czyCarbohydratesWPrzedziale()
        + czyFatWPrzedziale()
        + czyKcalWPrzedziale()
        + czyProteinWPrzedziale()
        + getCarbohydrates()
        + getFat()
        + getKcal()
        + getProtein()
    }
  }
  

  namespace Elements {
    class Elements.Product {
        - amountOfProduct : float
        - carbohydrates : float
        - fat : float
        - id : int
        - kcal : float
        - name : String
        - protein : float
        - referenceValue : int
        - unitOfMeasurement : String
        + Product()
        + Product()
        + getAmountOfProduct()
        + getCarbohydrates()
        + getFat()
        + getId()
        + getKcal()
        + getName()
        + getProtein()
        + getReferenceValue()
        + getUnitOfMeasurement()
        + setAmountOfProduct()
        + setCarbohydrates()
        + setFat()
        + setId()
        + setKcal()
        + setName()
        + setProtein()
        + setReferenceValue()
        + setUnitOfMeasurement()
        + toString()
        + wyliczIloscProduktu()
    }
  }
  

  namespace Elements {
    class Elements.ProduktParser {
        + Edytuj()
        + PobierzProduktyZDania()
        + Usun()
        + UsunPowiazane()
        + createSaveQuery()
        + pobierzJeden()
        + pobierzWszystkie()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
